/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSimuladorRouteImport } from './routes/_authenticated/simulador'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPlanoAcaoRouteImport } from './routes/_authenticated/plano-acao'
import { Route as AuthenticatedParcelamentosRouteImport } from './routes/_authenticated/parcelamentos'
import { Route as AuthenticatedLancamentosRouteImport } from './routes/_authenticated/lancamentos'
import { Route as AuthenticatedImportacaoRouteImport } from './routes/_authenticated/importacao'
import { Route as AuthenticatedExportacaoRouteImport } from './routes/_authenticated/exportacao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContasReceberRouteImport } from './routes/_authenticated/contas-receber'
import { Route as AuthenticatedContasPagarRouteImport } from './routes/_authenticated/contas-pagar'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAnaliseEfoRouteImport } from './routes/_authenticated/analise-efo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimuladorRoute = AuthenticatedSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanoAcaoRoute = AuthenticatedPlanoAcaoRouteImport.update({
  id: '/plano-acao',
  path: '/plano-acao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParcelamentosRoute =
  AuthenticatedParcelamentosRouteImport.update({
    id: '/parcelamentos',
    path: '/parcelamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosRoute =
  AuthenticatedLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportacaoRoute = AuthenticatedImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportacaoRoute = AuthenticatedExportacaoRouteImport.update({
  id: '/exportacao',
  path: '/exportacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContasReceberRoute =
  AuthenticatedContasReceberRouteImport.update({
    id: '/contas-receber',
    path: '/contas-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasPagarRoute =
  AuthenticatedContasPagarRouteImport.update({
    id: '/contas-pagar',
    path: '/contas-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnaliseEfoRoute = AuthenticatedAnaliseEfoRouteImport.update({
  id: '/analise-efo',
  path: '/analise-efo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analise-efo': typeof AuthenticatedAnaliseEfoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exportacao': typeof AuthenticatedExportacaoRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/parcelamentos': typeof AuthenticatedParcelamentosRoute
  '/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analise-efo': typeof AuthenticatedAnaliseEfoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exportacao': typeof AuthenticatedExportacaoRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/parcelamentos': typeof AuthenticatedParcelamentosRoute
  '/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analise-efo': typeof AuthenticatedAnaliseEfoRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/_authenticated/contas-receber': typeof AuthenticatedContasReceberRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exportacao': typeof AuthenticatedExportacaoRoute
  '/_authenticated/importacao': typeof AuthenticatedImportacaoRoute
  '/_authenticated/lancamentos': typeof AuthenticatedLancamentosRoute
  '/_authenticated/parcelamentos': typeof AuthenticatedParcelamentosRoute
  '/_authenticated/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/simulador': typeof AuthenticatedSimuladorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analise-efo'
    | '/clientes'
    | '/contas-pagar'
    | '/contas-receber'
    | '/dashboard'
    | '/exportacao'
    | '/importacao'
    | '/lancamentos'
    | '/parcelamentos'
    | '/plano-acao'
    | '/relatorios'
    | '/simulador'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analise-efo'
    | '/clientes'
    | '/contas-pagar'
    | '/contas-receber'
    | '/dashboard'
    | '/exportacao'
    | '/importacao'
    | '/lancamentos'
    | '/parcelamentos'
    | '/plano-acao'
    | '/relatorios'
    | '/simulador'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analise-efo'
    | '/_authenticated/clientes'
    | '/_authenticated/contas-pagar'
    | '/_authenticated/contas-receber'
    | '/_authenticated/dashboard'
    | '/_authenticated/exportacao'
    | '/_authenticated/importacao'
    | '/_authenticated/lancamentos'
    | '/_authenticated/parcelamentos'
    | '/_authenticated/plano-acao'
    | '/_authenticated/relatorios'
    | '/_authenticated/simulador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulador': {
      id: '/_authenticated/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof AuthenticatedSimuladorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano-acao': {
      id: '/_authenticated/plano-acao'
      path: '/plano-acao'
      fullPath: '/plano-acao'
      preLoaderRoute: typeof AuthenticatedPlanoAcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parcelamentos': {
      id: '/_authenticated/parcelamentos'
      path: '/parcelamentos'
      fullPath: '/parcelamentos'
      preLoaderRoute: typeof AuthenticatedParcelamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos': {
      id: '/_authenticated/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AuthenticatedLancamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importacao': {
      id: '/_authenticated/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof AuthenticatedImportacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exportacao': {
      id: '/_authenticated/exportacao'
      path: '/exportacao'
      fullPath: '/exportacao'
      preLoaderRoute: typeof AuthenticatedExportacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-receber': {
      id: '/_authenticated/contas-receber'
      path: '/contas-receber'
      fullPath: '/contas-receber'
      preLoaderRoute: typeof AuthenticatedContasReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-pagar': {
      id: '/_authenticated/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/contas-pagar'
      preLoaderRoute: typeof AuthenticatedContasPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analise-efo': {
      id: '/_authenticated/analise-efo'
      path: '/analise-efo'
      fullPath: '/analise-efo'
      preLoaderRoute: typeof AuthenticatedAnaliseEfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnaliseEfoRoute: typeof AuthenticatedAnaliseEfoRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedContasPagarRoute: typeof AuthenticatedContasPagarRoute
  AuthenticatedContasReceberRoute: typeof AuthenticatedContasReceberRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportacaoRoute: typeof AuthenticatedExportacaoRoute
  AuthenticatedImportacaoRoute: typeof AuthenticatedImportacaoRoute
  AuthenticatedLancamentosRoute: typeof AuthenticatedLancamentosRoute
  AuthenticatedParcelamentosRoute: typeof AuthenticatedParcelamentosRoute
  AuthenticatedPlanoAcaoRoute: typeof AuthenticatedPlanoAcaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSimuladorRoute: typeof AuthenticatedSimuladorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnaliseEfoRoute: AuthenticatedAnaliseEfoRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedContasPagarRoute: AuthenticatedContasPagarRoute,
  AuthenticatedContasReceberRoute: AuthenticatedContasReceberRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportacaoRoute: AuthenticatedExportacaoRoute,
  AuthenticatedImportacaoRoute: AuthenticatedImportacaoRoute,
  AuthenticatedLancamentosRoute: AuthenticatedLancamentosRoute,
  AuthenticatedParcelamentosRoute: AuthenticatedParcelamentosRoute,
  AuthenticatedPlanoAcaoRoute: AuthenticatedPlanoAcaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSimuladorRoute: AuthenticatedSimuladorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
